jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Application Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./firebase_service_account.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: export GOOGLE_APPLICATION_CREDENTIALS="./firebase_service_account.json"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Streamlit
        run: streamlit run app.py
